name: Bump Version and Create PR

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Select the version type'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Bump the version based on the user input
      - name: Bump version
        run: npm version ${{ github.event.inputs['version-type'] }}

      # Step 5: Commit the updated package.json
      - name: Commit version change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Bump version to $(npm pkg get version | tr -d '\"')"
          git push origin HEAD

      # Step 6: Create a Pull Request
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to $(npm pkg get version | tr -d '\"')"
          branch: version-bump-${{ github.event.inputs['version-type'] }}
          title: "Bump version to $(npm pkg get version | tr -d '\"')"
          body: |
            This pull request bumps the version to $(npm pkg get version | tr -d '\"').
          base: main
