name: Bump Version and Create PR

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Select the version type (patch, minor, major)'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set Git config
      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      # Step 6: Commit the updated package.json
      - name: Commit version change
        run: |
          git checkout -b VERSION-UPGRADE
          npm version ${{ github.event.inputs['version-type'] }}
          git status
          git add .
          git commit -m "Bump version"
          git push --set-upstream origin VERSION-UPGRADE --force

      # Step 8: Create a Pull Request
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version to $(npm pkg get version | tr -d '\"')"
          branch: VERSION-UPGRADE
          title: "Bump version to $(npm pkg get version | tr -d '\"')"
          body: |
            This pull request bumps the version to $(npm pkg get version | tr -d '\"').
          base: main
